# Generated by Django 2.0.5 on 2018-05-23 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.FileField(upload_to='course')),
                ('blob', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('instructor', models.ManyToManyField(to='instructor.Instructor')),
            ],
            options={
                'verbose_name_plural': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_chapter', models.PositiveIntegerField()),
                ('topic_title', models.CharField(max_length=200)),
                ('topic_description', models.TextField()),
                ('topic_duration', models.CharField(max_length=10)),
                ('topics_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.Course')),
            ],
            options={
                'verbose_name_plural': 'Topic',
            },
        ),
    ]
