# Generated by Django 2.0.5 on 2018-05-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20180523_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='subject',
            new_name='course',
        ),
    ]
