# Generated by Django 2.0.5 on 2018-05-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_instructor'),
        ('student', '0002_auto_20180523_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name_plural': 'Student'},
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.ManyToManyField(to='course.Course'),
        ),
    ]
