# Generated by Django 2.0.5 on 2018-05-24 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180523_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttakenquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_quizzes', to='quiz.Quiz'),
        ),
    ]
