# Generated by Django 2.0.5 on 2018-05-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_instructor'),
        ('teaching_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingassistant',
            name='course',
            field=models.ManyToManyField(to='course.Course'),
        ),
    ]
